version: "3"
services:
  db:
    image: mysql
    container_name: pulza-db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "8888:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pulza
      - MYSQL_DATABASE=development
  app:
    build: .
    container_name: pulza-app
    volumes:
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=pulza
    depends_on:
      - db
    command: "python3 manage.py runserver 0.0.0.0:8000"
    # command: tail -f /dev/null
  nginx:
    image: nginx
    container_name: pulza-nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  mysql_data:
